# action.yml
name: 'Test a device snap'
description: 'Test a device snap'
inputs:
  edgex_device_snap:
    description: "edgex_device_snap"
    required: true  
  edgex_service_name:
    description: "edgex_service_name"
    required: true  
  edgex_device_name:
    description: "edgex_device_name"
    required: true  
runs:
  using: composite
  steps:
    - name: Install dependencies
      run: |
        sudo snap install --edge edgexfoundry
        sudo snap install --edge ${{inputs.edgex_device_snap}}
        sudo snap start ${{inputs.edgex_device_snap}}.${{inputs.edgex_service_name}}
        echo "::error file=app.js,line=10,col=15::Something went wrong"
        curl http://localhost:48082/api/v1/device/name/${{inputs.edgex_device_name}}
      shell: bash
