name: Test this action
on: push
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test this action
        uses: siggiskulason/edgex-test-device-snap-action@v1.0
        with:
          edgex_device_snap: "edgex-device-camera"
          edgex_service_name: "device-camera-go"
          edgex_device_name: "Camera001"
